name: 🚀 Deploy website on push

on: 
  push:
    branches:
      - main
  
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest codeecho "# project-gitdock" >> README.md
git init
git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin git@github.com:EliottWCRT/project-gitdock.git
git push -u origin main
      uses: actions/checkout@v3

    - name: Use Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: '20'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PWD }}
        protocol: ${{ secrets.PROTOCOL }}
        local-dir: ./dist/
        server-dir: /htdocs/
